In [2]:
from examples import syllable_encoding
from indic_transliteration import sanscript
from indic_transliteration.sanscript import SchemeMap, SCHEMES, transliterate

In [5]:
text = transliterate('anujaH', sanscript.SLP1, sanscript.DEVANAGARI)
# text = "अ॒ग्निमी॑ळे"
''.join(syllable_encoding.syllabify(text)[-2:])

'नुजः'

In [4]:
stats = syllable_encoding.getSyllableStats(text)
for k, v in stats.items():
    print (k)
    for x, y in v.items():
        print ("\t", x, ":", y)
    print ("total", k, "=", sum(v.values()))
    print ("unique", k, "=", len(v), end='\n\n')

words
	 अ॒ग्निमी॑ळे : 1
total words = 1
unique words = 1

syllables
	 अ॒ : 1
	 ग्नि : 1
	 मी॑ : 1
	 ळे : 1
total syllables = 4
unique syllables = 4



In [29]:
mydict = dict()
mydict['True'] = 1
print()

True


In [1]:

files = os.listdir('./data/Rules/')
for file in files:
    
    break
data

0   1  2   3   4  5                      6      7                     8
0    0  11  1   9  13  1  #karwqsamAnAXikaraNam  25.1a  karwqsamanaxikaranam
1    1  11  1   7  13  1                 #karwA    1.2                 karwa
2    2  10  1   9  13  1  #karwqsamAnAXikaraNam  25.1a  karwqsamanaxikaranam
3    3  10  1   7  13  1                 #karwA    1.2                 karwa
4    4   9  2  34  11  1                 #hewuH   24.1                 hewuh
5    5   9  2  35  11  1        #RaRTIsambanXaH   20.6        rartisambanxah
6    6   9  2  35  10  1        #RaRTIsambanXaH   20.6        rartisambanxah
7    7   8  1  25  13  1            #aXikaraNam   3.23            axikaranam
8    8   7  1  34  11  1                 #hewuH   24.1                 hewuh
9    9   7  1  35  11  1        #RaRTIsambanXaH   20.6        rartisambanxah
10  10   7  1  35  10  1        #RaRTIsambanXaH   20.6        rartisambanxah
11  11   7  1  35   8  1        #RaRTIsambanXaH   20.6        rartisambanxah
12  12   6  1  28  13  1             #sambanXaH   38.2             sambanxah
13  13   6  1  44  13  1               #anuyogI   40.6      upapaxasambanxah
14  15   5  1   3   6  1             #prawiyogI   40.9             prawiyogi
15  17   4  2   3   6  1             #prawiyogI   40.5             prawiyogi
16  18   4  2   9  13  1  #karwqsamAnAXikaraNam   25.4  karwqsamanaxikaranam
17  19   4  2   9   5  1  #karwqsamAnAXikaraNam   25.4  karwqsamanaxikaranam
18  20   4  2   7  13  1                 #karwA    1.2                 karwa
19  21   4  2   7   5  1                 #karwA    1.2                 karwa
20  26   3  1   9  13  1  #karwqsamAnAXikaraNam  25.1a  karwqsamanaxikaranam
21  27   3  1   9   5  1  #karwqsamAnAXikaraNam  25.1a  karwqsamanaxikaranam
22  28   3  1   7  13  1                 #karwA    1.2                 karwa
23  29   3  1   7   5  1                 #karwA    1.2                 karwa
24  30   3  1  14   4  2                 #karma    2.2                 karma
25  31   2  1  24  13  1            #pUrvakAlaH    9.1            purvakalah
26  32   2  1  24   5  1            #pUrvakAlaH    9.1            purvakalah
27  33   2  1  24   4  2            #pUrvakAlaH    9.1            purvakalah
28  34   1  2  14   4  2                 #karma   2.7b                 karma
29  35   1  2  14   2  1                 #karma    4.6                 karma

In [16]:
import ast
import os
import pandas as pd
file = 'Gold_1132'
data = pd.read_csv('./data/Rules/rule_'+file,header=None,sep=',')
data
# temp = dict()
# if "Gold" in file:
#     temp.update({-1:{'Gold'}})
# else:
#     temp.update({-1:{'Eval'}})
# for i in range(len(data)):
#     temp.update({i: {data.iloc[i,1],data.iloc[i,4],data.iloc[i,-1]}})
# res = ast.literal_eval(str(temp))


0   1  2     3   4  5                   6      7                 8
0    0  11  7    35  13  3     #RaRTIsambanXaH   20.6    rartisambanxah
1    2  11  6    41  14  1         #prayojanam   3.10  upapaxasambanxah
2    3  11  1     7  14  1              #karwA    1.2             karwa
3    4   9  1  4100  14  1  #xeSAXikaraNam_upa   18.4        axikaranam
4    5   9  1  4100   5  2  #xeSAXikaraNam_upa   18.4        axikaranam
5    8   8  1  4100  14  1  #xeSAXikaraNam_upa   18.1        axikaranam
6    9   7  1    44  14  1            #anuyogI  37.3a  upapaxasambanxah
7   10   6  1    28   5  2          #sambanXaH   27.1         sambanxah
8   12   6  1    44  14  1            #anuyogI   41.4  upapaxasambanxah
9   13   5  2     3   7  1          #prawiyogI  37.3a         prawiyogi
10  14   5  2     3   6  1          #prawiyogI   41.3         prawiyogi
11  17   3  2    47  14  1          #samboXyaH   3.24         samboxyah
12  18   3  2    47   5  2          #samboXyaH   3.24         samboxyah
13  20   3  1     7  14  1              #karwA    1.2             karwa
14  21   3  1     7   5  2              #karwA    1.2             karwa
15  23   2  3    47  14  1          #samboXyaH   3.24         samboxyah
16  24   2  3    47   5  2          #samboXyaH   3.24         samboxyah
17  26   2  2    32  13  3          #viSeRaNam   12.1         viseranam
18  27   2  2    14   5  2              #karma   1.31             karma

In [19]:
file

'Gold_1132'

In [21]:
data = pd.read_csv('./data/sanskrit_treebank/train/'+file,header=None,sep=',')
data

FileNotFoundError: [Errno 2] File b'./data/sanskrit_treebank/train/Gold_1132' does not exist: b'./data/sanskrit_treebank/train/Gold_1132'

In [8]:
import torch
x = torch.rand(2, 2)
y = torch.rand(3,2,4)
x

tensor([[0.8195, 0.6815],
        [0.6887, 0.4983]])

In [12]:
y[1,1,1:]

tensor([0.1727, 0.1259, 0.9072])

In [9]:
x.unsqueeze(0)+y

tensor([[[1.0201, 0.9442],
         [1.4542, 1.1683]],

        [[1.3819, 1.1861],
         [0.9173, 1.6272]],

        [[1.3302, 0.7482],
         [0.9709, 1.0617]]])

In [3]:
def test(flag= True):
    if flag == False:
        print('yes')
    else:
        print('no')
      
test(flag=False)

yes
